name: Setup & Run
description: Setup Environment

inputs:
  script:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      with:
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@65beceff8e91358525397bdce9103d999507ab03
      with:
        node-version: '20'
        cache: 'npm'

    - name: Cache & install dependencies
      id: deps
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - run: npm ci
      shell: bash

    - name: Run npm script
      run: npm run ${{ inputs.script }}
      shell: bash

outputs:
  cache-hit:
    description: Whether node_modules was restored from cache
    value: ${{ steps.deps.outputs.cache-hit }}
